# Generated by Django 4.1 on 2022-08-16 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
